add description how to add the security group to the gpu node pool
dspace-group/simphera-reference-architecture-aws pull request #173
Opened 2024-10-31 09:53 UTC by ChristianBergen

add description how add the security group to the gpu node pool

2024-11-04 08:30 UTC, schwichti requested changes
So the problem is that you need to add a security group so that gpuexecnodes can talk with execnodes? Why can't we configure this in Terraform? I believe we already have a solution for a customer deployment and IVS node pool. I will get back to you on this.

2024-11-11 10:25 UTC, schwichti commented
I have not found the Terraform code where we did this. 

My suggestion is to create an issue with the problem description and your solution until the feature is implemented in Terraform and abandon this PR. 

Manual adjustments would be overriden by Terraform in subsequent runs.

2025-02-04 11:17 UTC, vradicevicds commented
This PR can be closed. Issue is fixed with https://github.com/dspace-group/simphera-reference-architecture-aws/pull/190.

2025-02-06 14:28 UTC, mariogluhakovic commented
It is fixed with different PR.

2025-02-06 14:28 UTC, closed without merging