Update main.tf
dspace-group/simphera-reference-architecture-aws pull request #73
Opened 2023-05-26 07:47 UTC by ChristianBergen

Set provider aws to NOT use version 5.0.0
- Version 5.0.0 does not support "enable_classiclink" for resource "aws_vpc" anymore.

2023-05-26 08:51 UTC, schwichti commented
Where is enable_classiclink used? Why we need it? How much afford is it to replace it?

2023-05-26 09:04 UTC, ChristianBergen commented
It is used in the main.tf of the module "simphera-ref.vpc" below resource "aws_vpc" "this". The other questions I cannot answer.

2023-05-26 09:11 UTC, schwichti requested changes

2023-05-26 10:17 UTC, ChristianBergen commented on main.tf
> +      version = "~> 4.47"
added comment

2023-05-30 09:37 UTC, schwichti approved these changes

2023-05-30 09:40 UTC, merged