Add gpu node pool
dspace-group/simphera-reference-architecture-aws pull request #74
Opened 2023-06-01 07:09 UTC by PhilippKorth

Adds the option to add a gpu powerd node pool to the eks cluster.

2023-06-12 08:01 UTC, schwichti requested changes

2023-06-12 08:01 UTC, schwichti commented on README.md
- Update readme.md
  - Update architecture diagram
  - Write 1-2 sentences what the gpu nodes are used for (Aurelion)

2023-06-29 05:22 UTC, PhilippKorth commented on README.md
I recreated the diagram with drawio. Could you check if this is ok for you?

2023-06-29 07:07 UTC, PhilippKorth commented on README.md
> +In case you want to add a gpu node pool to your architecture you might have to increase the [quota](https://docs.aws.amazon.com/servicequotas/latest/userguide/intro.html) for the gpu instance type yo
I removed the middle sentence

2023-07-03 06:02 UTC, schwichti approved these changes

2023-07-03 06:03 UTC, merged