Add EFS (elastic file system)
dspace-group/simphera-reference-architecture-aws pull request #75
Opened 2023-06-01 14:20 UTC by mariogluhakovic

- Add EFS (elastic file system) that is needed for measurement storage

2023-06-05 08:58 UTC, schwichti requested changes
* Update section *Billable Resources and Services* in README.md
* Update section *Architecture* in README.md
* Update section *Encryption* in README.md
* Is there a backup solution for the EFS? (if no, create a new issue for this for a separate PR).

2023-06-06 07:53 UTC, mariogluhakovic commented on storages.tf
> +    zone1 = module.vpc.private_subnets[0]
Changed.

2023-06-06 07:55 UTC, mariogluhakovic commented
> * Update section _Billable Resources and Services_ in README.md
> * Update section _Architecture_ in README.md
> * Update section _Encryption_ in README.md
> * Is there a backup solution for the EFS? (if no, create a new issue for this for a separate PR).

Readme is updated.
Backup solution is not needed since this is temporary storage for data analyze. The same data can be found inside the Minio storage and recreate by running the experiment.

2023-06-06 08:27 UTC, schwichti requested changes

2023-06-06 08:27 UTC, schwichti commented on README.md
> +| Amazon Elastic File System | Binary artifact are temporary stored in EFS | Yes |
Binary artifacts are stored temporarily in EFS.

2023-06-06 08:27 UTC, schwichti commented on AWSReferenceArchitecture.png
Please use either the old or new AWS icon set consistently.

2023-06-06 08:31 UTC, mariogluhakovic commented on AWSReferenceArchitecture.png
Done.

2023-06-06 08:47 UTC, schwichti approved these changes

2023-06-06 08:47 UTC, merged